apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-sftp-secrets
  labels:
    app: {{ .Chart.Name }}
type: Opaque
stringData:
  UPLOADER1_PUBLIC_KEY: "{{ .Values.sftp.uploader1.publicKey }}"
  UPLOADER2_PUBLIC_KEY: "{{ .Values.sftp.uploader2.publicKey }}"
  UPLOADER3_PUBLIC_KEY: "{{ .Values.sftp.uploader3.publicKey }}"
  UPLOADER1_USERNAME: "{{ .Values.sftp.uploader1.username }}"
  UPLOADER2_USERNAME: "{{ .Values.sftp.uploader2.username }}"
  UPLOADER3_USERNAME: "{{ .Values.sftp.uploader3.username }}"
  SERVICE_PUBLIC_KEY: "{{ .Values.sftp.service.publicKey }}"
  ADMIN_USER: "{{ .Values.sftp.admin.user }}"
  ADMIN_PASSWORD: "{{ .Values.sftp.admin.password }}"