apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-sftp-secrets
  labels:
    app: {{ .Chart.Name }}
type: Opaque
stringData:
  UPLOADER1_PUBLIC_KEY: "{{ .Values.sftp.uploader1.publicKey | nindent 4 }}"
  UPLOADER2_PUBLIC_KEY: "{{ .Values.sftp.uploader2.publicKey | nindent 4 }}"
  UPLOADER3_PUBLIC_KEY: "{{ .Values.sftp.uploader3.publicKey | nindent 4 }}"
  SERVICE_PUBLIC_KEY: "{{ .Values.sftp.service.publicKey | nindent 4 }}"
  ADMIN_USER: "{{ .Values.sftp.admin.user }}"
  ADMIN_PASSWORD: "{{ .Values.sftp.admin.password }}"