{{- if and .Values.global.secrets .Values.global.secrets.enabled}}
{{- $databaseUser := .Values.global.secrets.databaseUser| default "postgres"  }}
{{- $databaseSchema := .Values.global.secrets.databaseSchema| default "enmods"  }}
{{- $databasePassword := .Values.global.secrets.databasePassword | default (randAlphaNum 10) }}
{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "nr-enmods-dar") | default dict }}
{{- $secretData := (get $secretObj "data") | default dict }}
  # set below to existing secret data or generate a random one when not exists
{{- $databasePassword = (get $secretData "databasePassword" | default ($databasePassword | b64enc)) }}
{{- $databaseName := .Values.global.secrets.databaseName| default "postgres" }}
{{- $host := printf "%s-%s:5432" .Release.Name .Values.global.databaseAlias }}
{{- $hostWithoutPort := printf "%s-%s" .Release.Name .Values.global.databaseAlias }}
{{- $databaseURL := printf "postgresql://%s:%s@%s/%s" $databaseUser (b64dec $databasePassword) $host $databaseName }}
{{- $databaseJDBCURL := printf "jdbc:postgresql://%s:%s@%s/%s" $databaseUser (b64dec $databasePassword) $host $databaseName }}
{{- $databaseJDBCURLNoCreds := printf "jdbc:postgresql://%s/%s" $host $databaseName }}
{{- $databasePort := (get $secretData "databasePort") | default "5432" }}
    
#-- backend
{{- $prismaLogging := (get $secretData "prismaLogging" | b64dec | default "") }}
{{- $keycloakClientId := (get $secretData "keycloakClientId" | b64dec | default "") }}
{{- $jwksUri := (get $secretData "jwksUri" | b64dec | default "") }}
{{- $jwtIssuer := (get $secretData "jwtIssuer" | b64dec | default "") }}
{{- $usersApiBaseUrl := (get $secretData "usersApiBaseUrl" | b64dec | default "") }}
{{- $cssEnvironment := (get $secretData "cssEnvironment" | b64dec | default "") }}
{{- $integrationId := (get $secretData "integrationId" | b64dec | default "") }}
{{- $usersApiTokenUrl := (get $secretData "usersApiTokenUrl" | b64dec | default "") }}
{{- $usersApiClientId := (get $secretData "usersApiClientId" | b64dec | default "") }}
{{- $usersApiClientSecret := (get $secretData "usersApiClientSecret" | b64dec | default "") }}
{{- $aqiBaseUrl := (get $secretData "aqiBaseUrl" | b64dec | default "") }}
{{- $aqiAccessToken := (get $secretData "aqiAccessToken" | b64dec | default "") }}
{{- $chesTokenUrl := (get $secretData "chesTokenUrl" | b64dec | default "") }}
{{- $chesEmailUrl := (get $secretData "chesEmailUrl" | b64dec | default "") }}
{{- $chesClientId := (get $secretData "chesClientId" | b64dec | default "") }}
{{- $chesClientSecret := (get $secretData "chesClientSecret" | b64dec | default "") }}
{{- $webappUrl := (get $secretData "webappUrl" | b64dec | default "") }}
{{- $ftpPath := (get $secretData "ftpPath" | b64dec | default "") }}
{{- $ftpHost := (get $secretData "ftpHost" | b64dec | default "") }}
{{- $ftpPort := (get $secretData "ftpPort" | b64dec | default "") }}
{{- $ftpUser := (get $secretData "ftpUser" | b64dec | default "") }}
{{- $ftpPassword := (get $secretData "ftpPassword" | b64dec | default "") }}
{{- $databaseServiceName := (get $secretData "databaseServiceName" | b64dec | default "") }}
{{- $objectstoreAccessKey := (get $secretData "objectstoreAccessKey" | b64dec | default "") }}
{{- $objectstoreUrl := (get $secretData "objectstoreUrl" | b64dec | default "") }}
{{- $objectstoreBucket := (get $secretData "objectstoreBucket" | b64dec | default "") }}
{{- $objectstoreSecretKey := (get $secretData "objectstoreSecretKey" | b64dec | default "") }}

#-- frontend

{{- $apiName := (get $secretData "apiName" | b64dec | default "") }}
{{- $baseUrl := (get $secretData "baseUrl" | b64dec | default "") }}
{{- $viteAppApiUrl := .Values.global.secrets.viteAppApiUrl| default "/api" }}
{{- $viteAppKeycloakUrl := (get $secretData "viteAppKeycloakUrl" | b64dec | default "") }}
{{- $viteAppKeycloakUrl2 := (get $secretData "viteAppKeycloakUrl2" | b64dec | default "") }}
{{- $viteAppKeycloakRealm := (get $secretData "viteAppKeycloakRealm" | b64dec | default "") }}
{{- $viteAppKeycloakClientId := (get $secretData "viteAppKeycloakClientId" | b64dec | default "") }}
{{- $viteAppKeycloakUser := (get $secretData "viteAppKeycloakUser" | b64dec | default "") }}
{{- $viteAppKeycloakPassword := (get $secretData "viteAppKeycloakPassword" | b64dec | default "") }}
#-- backup
{{- $backupDir := (get $secretData "backupDir" | b64dec | default "") }}
{{- $backupStrategy := (get $secretData "backupStrategy" | b64dec | default "") }}
{{- $numBackups := (get $secretData "numBackups" | b64dec | default "") }}
{{- $dailyBackups := (get $secretData "dailyBackups" | b64dec | default "") }}
{{- $weeklyBackups := (get $secretData "weeklyBackups" | b64dec | default "") }}
{{- $monthlyBackups := (get $secretData "monthlyBackups" | b64dec | default "") }}


---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend
  labels: {{- include "labels" . | nindent 4 }}
  {{- if .Values.global.secrets.persist }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
data:
  # BACKEND Secrets
  POSTGRES_PASSWORD: {{ $databasePassword | quote }}
  POSTGRES_USER: {{  $databaseUser | b64enc | quote }}
  POSTGRES_DATABASE: {{ $databaseName | b64enc | quote }}
  POSTGRES_HOST: {{ $hostWithoutPort | b64enc | quote }}
  POSTGRESQL_URL: {{ $databaseURL | b64enc | quote }}
  POSTGRES_PORT: {{ $databasePort | b64enc | quote }}
  POSTGRES_SCHEMA: {{ $databaseSchema | b64enc | quote }}
  PRISMA_LOGGING: {{ $prismaLogging | b64enc | quote }}
  KEYCLOCK_CLIENT_ID: {{ $keycloakClientId | b64enc | quote }}
  JWKS_URI: {{ $jwksUri | b64enc | quote }}
  JWT_ISSUER: {{ $jwtIssuer | b64enc | quote }}
  USERS_API_BASE_URL: {{ $usersApiBaseUrl | b64enc | quote }}
  CSS_ENVIRONMENT: {{ $cssEnvironment | b64enc | quote }}
  INTEGRATION_ID: {{ $integrationId | b64enc | quote }}
  USERS_API_TOKEN_URL: {{ $usersApiTokenUrl | b64enc | quote }}
  USERS_API_CLIENT_ID: {{ $usersApiClientId | b64enc | quote }}
  USERS_API_CLIENT_SECRET: {{ $usersApiClientSecret | b64enc | quote }}
  AQI_BASE_URL: {{ $aqiBaseUrl | b64enc | quote }}
  AQI_ACCESS_TOKEN: {{ $aqiAccessToken | b64enc | quote }}
  CHES_TOKEN_URL: {{ $chesTokenUrl | b64enc | quote }}
  CHES_EMAIL_URL: {{ $chesEmailUrl | b64enc | quote }}
  CHES_CLIENT_ID: {{ $chesClientId | b64enc | quote }}
  CHES_CLIENT_SECRET: {{ $chesClientSecret | b64enc | quote }}
  WEBAPP_URL: {{ $webappUrl | b64enc | quote }}
  FTP_PATH: {{ $ftpPath | b64enc | quote }}
  FTP_HOST: {{ $ftpHost | b64enc | quote }}
  FTP_PORT: {{ $ftpPort | b64enc | quote }}
  FTP_USER: {{ $ftpUser | b64enc | quote }}
  FTP_PASSWORD: {{ $ftpPassword | b64enc | quote }}
  # BACKUP Secrets - unsure if needed
  BACKUP_DIR: {{ $backupDir | b64enc | quote }}
  BACKUP_STRATEGY: {{ $backupStrategy | b64enc | quote }}
  NUM_BACKUPS: {{ $numBackups | b64enc | quote }}
  DAILY_BACKUPS: {{ $dailyBackups | b64enc | quote }}
  WEEKLY_BACKUPS: {{ $weeklyBackups | b64enc | quote }}
  MONTHLY_BACKUPS: {{ $monthlyBackups | b64enc | quote }}
  DATABASE_SERVICE_NAME: {{ $databaseServiceName | b64enc | quote }}
  OBJECTSTORE_ACCESS_KEY: {{ $objectstoreAccessKey | b64enc | quote }}
  OBJECTSTORE_URL: {{ $objectstoreUrl | b64enc | quote }}
  OBJECTSTORE_BUCKET: {{ $objectstoreBucket | b64enc | quote }}
  OBJECTSTORE_SECRET_KEY: {{ $objectstoreSecretKey | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-frontend
  labels: {{- include "labels" . | nindent 4 }}
  {{- if .Values.global.secrets.persist }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
data:
  # FRONTEND Secrets
  PORT:  {{ .Values.global.secrets.port | b64enc }}
  VITE_APP_API_URL: {{  .Values.global.secrets.viteAppApiUrl | b64enc | quote }}
  VITE_APP_KEYCLOAK_URL: {{ $viteAppKeycloakUrl | b64enc | quote }}
  VITE_APP_KEYCLOAK_URL_2: {{ $viteAppKeycloakUrl2 | b64enc | quote }}
  VITE_APP_KEYCLOAK_REALM: {{ $viteAppKeycloakRealm | b64enc | quote }}
  VITE_APP_KEYCLOAK_CLIENT_ID: {{ $viteAppKeycloakClientId | b64enc | quote }}
  VITE_APP_KEYCLOAK_USER: {{ $viteAppKeycloakUser | b64enc | quote }}
  VITE_APP_KEYCLOAK_PASSWORD: {{ $viteAppKeycloakPassword | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-flyway
  labels: {{- include "labels" . | nindent 4 }}
  {{- if .Values.global.secrets.persist }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
data:
  # FLYWAY Secrets
  FLYWAY_URL: {{ $databaseJDBCURLNoCreds | b64enc | quote }}
  FLYWAY_USER: {{ $databaseUser | b64enc | quote }}
  FLYWAY_PASSWORD: {{ $databasePassword | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-database
  labels: {{- include "labels" . | nindent 4 }}
  {{- if .Values.global.secrets.persist }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
data:
  postgres-password: {{ $databasePassword  | quote }}
  password: {{ $databasePassword | quote }}

{{- end }}