{{- if and .Values.global.secrets .Values.global.secrets.enabled}}
{{- $databaseUser := .Values.global.secrets.databaseUser| default "postgres"  }}
{{- $databaseSchema := .Values.global.secrets.databaseSchema| default "enmods"  }}
{{- $databasePassword := .Values.global.secrets.databasePassword | default (randAlphaNum 10) }}
{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "nr-enmods-dar") | default dict }}
{{- $secretData := (get $secretObj "data") | default dict }}
  # set below to existing secret data or generate a random one when not exists
{{- $databasePassword = (get $secretData "databasePassword" | default ($databasePassword | b64enc)) }}
{{- $databaseName := .Values.global.secrets.databaseName| default "postgres" }}
{{- $host := printf "%s-%s:5432" .Release.Name .Values.global.databaseAlias }}
{{- $hostWithoutPort := printf "%s-%s" .Release.Name .Values.global.databaseAlias }}
{{- $databaseURL := printf "postgresql://%s:%s@%s/%s?connection_limit=100&pool_limit=50" $databaseUser (b64dec $databasePassword) $host $databaseName }}
{{- $databaseJDBCURL := printf "jdbc:postgresql://%s:%s@%s/%s" $databaseUser (b64dec $databasePassword) $host $databaseName }}
{{- $databaseJDBCURLNoCreds := printf "jdbc:postgresql://%s/%s" $host $databaseName }}
{{- $databasePort := (get $secretData "databasePort") | default "5432" }}
    
#-- backend
{{- $prismaLogging := (get $secretData "prismaLogging" | b64dec | default "") }}
{{- $keycloakClientId := (get $secretData "keycloakClientId" | b64dec | default "") }}
{{- $jwksUri := (get $secretData "jwksUri" | b64dec | default "") }}
{{- $jwtIssuer := (get $secretData "jwtIssuer" | b64dec | default "") }}
{{- $usersApiBaseUrl := (get $secretData "usersApiBaseUrl" | b64dec | default "") }}
{{- $cssEnvironment := (get $secretData "cssEnvironment" | b64dec | default "") }}
{{- $integrationId := (get $secretData "integrationId" | b64dec | default "") }}
{{- $usersApiTokenUrl := (get $secretData "usersApiTokenUrl" | b64dec | default "") }}
{{- $usersApiClientId := (get $secretData "usersApiClientId" | b64dec | default "") }}
{{- $usersApiClientSecret := (get $secretData "usersApiClientSecret" | b64dec | default "") }}
{{- $aqiBaseUrl := (get $secretData "aqiBaseUrl" | b64dec | default "") }}
{{- $aqiAccessToken := (get $secretData "aqiAccessToken" | b64dec | default "") }}
{{- $chesTokenUrl := (get $secretData "chesTokenUrl" | b64dec | default "") }}
{{- $chesEmailUrl := (get $secretData "chesEmailUrl" | b64dec | default "") }}
{{- $chesClientId := (get $secretData "chesClientId" | b64dec | default "") }}
{{- $chesClientSecret := (get $secretData "chesClientSecret" | b64dec | default "") }}
{{- $webappUrl := (get $secretData "webappUrl" | b64dec | default "") }}
{{- $sftpPath := (get $secretData "sftpPath" | b64dec | default "") }}
{{- $sftpHost := (get $secretData "sftpHost" | b64dec | default "") }}
{{- $sftpPort := (get $secretData "sftpPort" | b64dec | default "") }}
{{- $sftpUsername := (get $secretData "sftpUsername" | b64dec | default "") }}
{{- $sftpPrivateKeyBase64 := (get $secretData "sftpPrivateKeyBase64" | b64dec | default "") }}
{{- $databaseServiceName := (get $secretData "databaseServiceName" | b64dec | default "") }}
{{- $objectstoreAccessKey := (get $secretData "objectstoreAccessKey" | b64dec | default "") }}
{{- $objectstoreUrl := (get $secretData "objectstoreUrl" | b64dec | default "") }}
{{- $objectstoreBucket := (get $secretData "objectstoreBucket" | b64dec | default "") }}
{{- $objectstoreBucketName := (get $secretData "objectstoreBucketName" | b64dec | default "") }}
{{- $objectstoreSecretKey := (get $secretData "objectstoreSecretKey" | b64dec | default "") }}
{{- $comsUri := (get $secretData "comsUri" | b64dec | default "") }}
{{- $comsBucketId := (get $secretData "comsBucketId" | b64dec | default "") }}


#-- frontend

{{- $apiName := (get $secretData "apiName" | b64dec | default "") }}
{{- $baseUrl := (get $secretData "baseUrl" | b64dec | default "") }}
{{- $reactAppApiUrl := .Values.global.secrets.reactAppApiUrl| default "/api" }}
{{- $reactAppKeycloakUrl := (get $secretData "reactAppKeycloakUrl" | b64dec | default "") }}
# {{- $reactAppKeycloakUrl2 := (get $secretData "reactAppKeycloakUrl2" | b64dec | default "") }}
{{- $reactAppKeycloakRealm := (get $secretData "reactAppKeycloakRealm" | b64dec | default "") }}
{{- $reactAppKeycloakClientId := (get $secretData "reactAppKeycloakClientId" | b64dec | default "") }}
# {{- $reactAppKeycloakUser := (get $secretData "reactAppKeycloakUser" | b64dec | default "") }}
# {{- $reactAppKeycloakPassword := (get $secretData "reactAppKeycloakPassword" | b64dec | default "") }}
#-- backup
{{- $backupDir := (get $secretData "backupDir" | b64dec | default "") }}
{{- $backupStrategy := (get $secretData "backupStrategy" | b64dec | default "") }}
{{- $numBackups := (get $secretData "numBackups" | b64dec | default "") }}
{{- $dailyBackups := (get $secretData "dailyBackups" | b64dec | default "") }}
{{- $weeklyBackups := (get $secretData "weeklyBackups" | b64dec | default "") }}
{{- $monthlyBackups := (get $secretData "monthlyBackups" | b64dec | default "") }}


---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend
  labels: {{- include "labels" . | nindent 4 }}
  {{- if .Values.global.secrets.persist }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
data:
  # BACKEND Secrets
  POSTGRES_PASSWORD: {{ $databasePassword | quote }}
  POSTGRES_USER: {{  $databaseUser | b64enc | quote }}
  POSTGRES_DATABASE: {{ $databaseName | b64enc | quote }}
  POSTGRES_HOST: {{ $hostWithoutPort | b64enc | quote }}
  POSTGRESQL_URL: {{ $databaseURL | b64enc | quote }}
  POSTGRES_PORT: {{ $databasePort | b64enc | quote }}
  POSTGRES_SCHEMA: {{ $databaseSchema | b64enc | quote }}
  PRISMA_LOGGING: {{ $prismaLogging | b64enc | quote }}
  KEYCLOAK_CLIENT_ID: {{ $keycloakClientId | b64enc | quote }}
  JWKS_URI: {{ $jwksUri | b64enc | quote }}
  JWT_ISSUER: {{ $jwtIssuer | b64enc | quote }}
  USERS_API_BASE_URL: {{ $usersApiBaseUrl | b64enc | quote }}
  CSS_ENVIRONMENT: {{ $cssEnvironment | b64enc | quote }}
  INTEGRATION_ID: {{ $integrationId | b64enc | quote }}
  USERS_API_TOKEN_URL: {{ $usersApiTokenUrl | b64enc | quote }}
  USERS_API_CLIENT_ID: {{ $usersApiClientId | b64enc | quote }}
  USERS_API_CLIENT_SECRET: {{ $usersApiClientSecret | b64enc | quote }}
  AQI_BASE_URL: {{ $aqiBaseUrl | b64enc | quote }}
  AQI_ACCESS_TOKEN: {{ $aqiAccessToken | b64enc | quote }}
  CHES_TOKEN_URL: {{ $chesTokenUrl | b64enc | quote }}
  CHES_EMAIL_URL: {{ $chesEmailUrl | b64enc | quote }}
  CHES_CLIENT_ID: {{ $chesClientId | b64enc | quote }}
  CHES_CLIENT_SECRET: {{ $chesClientSecret | b64enc | quote }}
  WEBAPP_URL: {{ $webappUrl | b64enc | quote }}
  SFTP_PATH: {{ $sftpPath | b64enc | quote }}
  SFTP_HOST: {{ $sftpHost | b64enc | quote }}
  SFTP_PORT: {{ $sftpPort | b64enc | quote }}
  SFTP_USERNAME: {{ $sftpUsername | b64enc | quote }}
  SFTP_PRIVATE_KEY_BASE64: {{ $sftpPrivateKeyBase64 | quote }}
  # BACKUP Secrets - unsure if needed
  BACKUP_DIR: {{ $backupDir | b64enc | quote }}
  BACKUP_STRATEGY: {{ $backupStrategy | b64enc | quote }}
  NUM_BACKUPS: {{ $numBackups | b64enc | quote }}
  DAILY_BACKUPS: {{ $dailyBackups | b64enc | quote }}
  WEEKLY_BACKUPS: {{ $weeklyBackups | b64enc | quote }}
  MONTHLY_BACKUPS: {{ $monthlyBackups | b64enc | quote }}
  DATABASE_SERVICE_NAME: {{ $databaseServiceName | b64enc | quote }}
  OBJECTSTORE_ACCESS_KEY: {{ $objectstoreAccessKey | b64enc | quote }}
  OBJECTSTORE_URL: {{ $objectstoreUrl | b64enc | quote }}
  OBJECTSTORE_BUCKET: {{ $objectstoreBucket | b64enc | quote }}
  OBJECTSTORE_BUCKET_NAME: {{ $objectstoreBucketName | b64enc | quote }}
  OBJECTSTORE_SECRET_KEY: {{ $objectstoreSecretKey | b64enc | quote }}
  COMS_URI: {{ $comsUri | b64enc | quote }}
  COMS_BUCKET_ID: {{ $comsBucketId | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-frontend
  labels: {{- include "labels" . | nindent 4 }}
  {{- if .Values.global.secrets.persist }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
data:
  # FRONTEND Secrets
  PORT:  {{ .Values.global.secrets.port | b64enc }}
  REACT_APP_API_URL: {{  .Values.global.secrets.reactAppApiUrl | b64enc | quote }}
  REACT_APP_KEYCLOAK_URL: {{ $reactAppKeycloakUrl | b64enc | quote }}
  REACT_APP_KEYCLOAK_URL_2: {{ $reactAppKeycloakUrl2 | b64enc | quote }}
  REACT_APP_KEYCLOAK_REALM: {{ $reactAppKeycloakRealm | b64enc | quote }}
  REACT_APP_KEYCLOAK_CLIENT_ID: {{ $reactAppKeycloakClientId | b64enc | quote }}
  REACT_APP_KEYCLOAK_USER: {{ $reactAppKeycloakUser | b64enc | quote }}
  REACT_APP_KEYCLOAK_PASSWORD: {{ $reactAppKeycloakPassword | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-flyway
  labels: {{- include "labels" . | nindent 4 }}
  {{- if .Values.global.secrets.persist }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
data:
  # FLYWAY Secrets
  FLYWAY_URL: {{ $databaseJDBCURLNoCreds | b64enc | quote }}
  FLYWAY_USER: {{ $databaseUser | b64enc | quote }}
  FLYWAY_PASSWORD: {{ $databasePassword | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-database
  labels: {{- include "labels" . | nindent 4 }}
  {{- if .Values.global.secrets.persist }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
data:
  postgres-password: {{ $databasePassword  | quote }}
  password: {{ $databasePassword | quote }}

{{- end }}